# environments.yml
name: streamlit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scikit-learn
  - pandas=1.3.3
  - numpy
  - pytest
  - ipython
  - jupyter
  - jupyterlab
  - matplotlib
  - seaborn
  - plotly
  - pylint
  - streamlit
  - altair
  - bokeh
  - pillow
  - opencv
  - pandas-profiling
  - streamlit-pandas-profiling
  - pydantic<2.0.0

